<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWPF>true</UseWPF>
    <Configurations>Debug;Release</Configurations>
    <Platforms>x86;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MediaCaptureWPF.Native\MediaCaptureWPF.Native.vcxproj" />
  </ItemGroup>
</Project>